service: crud-serverless

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    minify: true
    external:
      - aws-sdk
    watch:
      pattern: [ './index.ts', 'src/**/*.ts' ]
      ignore: [ '.serverless/**/*', '.build' ]

functions:
  find-user:
    handler: src/functions/users/find.handler
    events:
      - http:
          path: users/{id}
          method: GET
  create-user:
    handler: src/functions/users/create.handler
    events:
      - http:
          path: users
          method: POST
  update-user:
    handler: src/functions/users/update.handler
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-user:
    handler: src/functions/users/delete.handler
    events:
      - http:
          path: users/{id}
          method: DELETE