service: crud-serverless

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    minify: true
    external:
      - aws-sdk
    watch:
      pattern: [ './index.ts', 'src/**/*.ts' ]
      ignore: [ '.serverless/**/*', '.build' ]

functions:
  - ${file(./src/functions/users/index.functions.yml)}